### ISSUE TITLE
color indicator for http version used

### ISSUE THREAD

**Issue by hpvd** [bsiegel/http-version-indicator#17]
Many thanks for adding http/3 support to your addon!

Just updated the addon in my ff 89b4.

what I found was that the color change of the icon depending on http version used by the website seems to be gone.
As far as I remember before the update the icon was blue for http/2.

Since the addon support reporting of all http versions, it would be awesome to have a color defined for each version, so one see which version is used without having to hover the icon.
e.g.
http/1.x = grey
http/2 = blue (as before)
http/3 = green

**Comment by Nothing4You** [comment]
in https://github.com/bsiegel/http-version-indicator/issues/13#issuecomment-804876401 this was still working, i believe i tested that with f858539 which was commented just before that

**Comment by hpvd** [comment]
detail: used the version provided via automatic addon update in ff (v3.2 from 27.04.2021)

**Comment by Nothing4You** [comment]
https://github.com/bsiegel/http-version-indicator/commit/ad2c95de30aa798869fe64d8efe25d66f4a5e777 removed the various icons because
> Firefox now applies a greyscale filter anyway, so the colors no longer
show up.

**Comment by hpvd** [comment]
ah ok, so one could try different color saturations
- light grey: http/1.x 
- mid grey http/2 
- dark grey: http/3 

or working with hollow and solid/filled icons: hollow, mixed, solid

or adding the number of http next to lightning symbol: 1,2,3

**Comment by hpvd** [comment]
just llooking on other icons in this area (indicateTLS): there is room for saturations and for a number:
![2021-04-27_13h05_14](https://user-images.githubusercontent.com/5681880/116231763-95acf480-a759-11eb-8954-eb3949b20322.png)

**Comment by Nothing4You** [comment]
Seems to be a result of the Proton redesign.
This is how the old version with colors looks in nightly (left) and 88 (right):
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/3694534/116231552-5088c280-a759-11eb-9928-77cc78f4157e.png">

Using different symbols or at adding some sort of identifier there certainly would help.

I don't think varying grayscale is really readable.

**Comment by Nothing4You** [comment]
It doesn't seem to be a requirement (yet?) though to use grayscale?
IndicateTLS still has colors in nightly:
<img width="824" alt="image" src="https://user-images.githubusercontent.com/3694534/116232140-00f6c680-a75a-11eb-99f3-36f1116db45b.png">

**Comment by hpvd** [comment]
same for ff owns bookmark:
![2021-04-27_13h13_52](https://user-images.githubusercontent.com/5681880/116232524-88dcd080-a75a-11eb-9124-33655adb695c.png)

**Comment by hpvd** [comment]
some more colors used by indicateTLS:
![2021-04-27_13h17_14](https://user-images.githubusercontent.com/5681880/116232888-fa1c8380-a75a-11eb-8a8b-f4f23633c4a7.png)

**Comment by bsiegel** [comment]
Thanks for the thorough research! I did a little investigation and it seems like the grayscale filter is applied:

1. Only for SVG icons, and
2. Only on the dark variant of the new Proton theme

I'll restore the colorful icons so that at least you'll get colors when the light theme is active, and I'll think through the best way to handle this for the dark theme. I could rasterize them into PNGs and then the grayscale filter would not be applied, but I might want to make alternate "dark mode" versions that are less bright.
